### ISSUE TITLE
Does not work with jQuery 3.0

### ISSUE THREAD

**Issue by eat-sleep-code** [jeremyfry/PikaChoose#22]
The following error is thrown when trying to load PikeChoose with jQuery 3.0
_jQuery.Deferred exception: this.clip.size is not a function TypeError: this.clip.size is not a function_

**Comment by dmethvin** [comment]
The error seems to be coming from the jCarousel dependency, it is using `.size()` which has been removed in 3.0. Either use [jQuery Migrate 3.0](https://github.com/jquery/jquery-migrate#readme) or update jCarousel since it's been fixed there: https://github.com/jsor/jcarousel/issues/800

**Comment by eat-sleep-code** [comment]
Actually, ended up ditching Pikachoose altogether.  jCarousel's connected carousel's demo with the touch plugin got me the functionality I needed.
